services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  api:
    build:
      context: .
    image: catalog-api
    container_name: catalog-api
    depends_on:
      - elasticsearch
    environment:
      - PORT=3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "3000:3000"

  loader:
    image: curlimages/curl:8.10.1
    depends_on:
      - elasticsearch
    volumes:
      - ./load-sample-data.sh:/load-sample-data.sh
    entrypoint: ["/bin/sh", "-c", "sleep 20 && sh /load-sample-data.sh"]

volumes:
  es-data:
